name: Bug report
description: Tell us about a bug you may have identified in Bootstrap.
title: "Provide a general summary of the issue"
labels: [ bug ]
assignees: "-"
body:
  - type: markdown
    attributes:
      value: "## Thanks for taking the time to fill out this bug report!"
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
          required: true
        - label: I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
          required: true
        - label: I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a general summary of the issue and you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how to recreate the issue.
      placeholder: |
        1. [First step]
        2. [Second step]
        3. [and so on...]
    validations:
      required: true
  - type: input
    id: reduced-test-case
    attributes:
      label: Reduced test case
      description: Include links to a [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/).
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Bootstrap 4 [template](https://codepen.io/team/bootstrap/pen/yLabNQL) | Bootstrap 5 [template](https://codepen.io/team/bootstrap/pen/qBamdLj)"
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
  - type: dropdown
    id: version
    attributes:
      label: What version of Bootstrap are you using?
      multiple: true
      options:
        - 3
        - 4
        - 5
    validations:
      required: true
